### ISSUE TITLE
Which imagestreams to use?

### ISSUE THREAD

**Issue by jorgemoralespou** [bucharest-gold/centos7-s2i-nodejs#117]
Reading the README points to an imagestream that does not exist.
Furthermore, in the imagestreams folder there are 2 imagestreams for nodejs-centos, one in json and another one in yaml, which are not related.

**Comment by lance** [comment]
@jorgemoralespou thanks for pointing out these issues. The `.yml` imagestream file was stale and should have been removed a while ago. Apologies for the confusion!
