### ISSUE TITLE
run `npm build` during assemble?

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/centos7-s2i-nodejs#135]
the SCL image does this, https://github.com/sclorg/s2i-nodejs-container/blob/master/8/s2i/bin/assemble#L81-L88

I'm not sure how i feel about it.  I suppose it is a nice feature, especially for those that are using typescript/babel/etc.....   I think currently the only way to do that now, is to have a `postinstall` script in the package.json that runs the build

**Comment by lance** [comment]
I think it's better than requiring a `postinstall` script, which isn't very intuitive and requires documentaiton.
