### ISSUE TITLE
node version 8.12.0 does "npm install -s --only=production"

### ISSUE THREAD

**Issue by uocxp** [bucharest-gold/centos7-s2i-nodejs#152]
in version 10 the script installs all the dependencies and them prune them. In version 8.12.0 on the other hand  only production dependencies are installed, which leads to missing dependencies. 
In my package.json i have `"build": "tsc", "postinstall": "npm run build"` . 
when the build script is called comes out **sh: tsc: command not found**

**Comment by lholmquist** [comment]
So the 8.x branch does have the commit that adds the this "build" workflow, however, i don't think it is in the image yet in docker hub.

There is also another PR that deals with making the s2i image smarter about not installing everything and then pruning, which is here https://github.com/bucharest-gold/centos7-s2i-nodejs/pull/150

You can set NODE_ENV=development which will make your dev dependecies get installed during the assemble phase, but that env var gets carried into the run phase, so you would have to set NODE_ENV=production when running the actual app.   

How are you using the image? like, what commands do you use?  i can probably tell you the best way to set those env vars based on your answer

**Comment by uocxp** [comment]
I imported the nodejs-centos7.json template in openshift and then i chose 8-RHOAR.
When setting the NODE_ENV=development the container works as expected. As you mentioned i must then set the NODE_ENV.

**Comment by uocxp** [comment]
can any body add the "build" workflow to the image ?

**Comment by lholmquist** [comment]
@uocxp i've just published an updated 8.x and 8.12.0 image with the changes from #150

**Comment by uocxp** [comment]
thanks a lot :)
