### ISSUE TITLE
problem when using the latest version of s2i tool

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/centos7-s2i-nodejs#17]
```console
BUILDER=bucharestgold/centos7-s2i-nodejs:8.x NODE_VERSION=8.3.0 ./test/run.sh
Running s2i build --force-pull=false  file://./test/test-app bucharestgold/centos7-s2i-nodejs:8.x bucharestgold/centos7-s2i-nodejs-testapp
Error: unknown flag: --force-pull
```

Downgrading to 1.1.5 solves the issue.
https://github.com/openshift/source-to-image/releases

**Comment by lance** [comment]
The deprecated `--force-pull` option was removed in [1.1.60(https://github.com/openshift/source-to-image/releases/tag/v1.1.6). We can use `--pull-policy` instead.

`-p, --pull-policy string               Specify when to pull the builder image (always, never or if-not-present) (default "if-not-present")`
