### ISSUE TITLE
I did something diff/wrong 

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/centos7-s2i-nodejs#19]
The version 8.3.0 is on dockerhub and workin, but I'm not following whats happened to the branch

```
14:36 $ git push origin origin/8.x 
Everything up-to-date
```

I'm trying to push the changes to the 8.x github branch

**Comment by danbev** [comment]
> $ git push origin origin/8.x

Should that be upstream/8.x perhaps?

**Comment by helio-frota** [comment]
@danbev thanks, but unfortunately no. I'm using only the main repo : /

```
15:15 $ git branch -a
* (HEAD detached at origin/8.x)
  master
  remotes/origin/4.x
  remotes/origin/5.x
  remotes/origin/6.x
  remotes/origin/7.x
  remotes/origin/8.x
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
✔ ~/d/centos7-s2i-nodejs [node-8.2.1|✔] 
```

**Comment by helio-frota** [comment]
I'm going to delete this local repo and start all again but **without** publish part.

**Comment by helio-frota** [comment]
from the docs:
https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/PUBLISHING.md#updating-node-versions
> Note that these files are kept up to date in the master branch, but any changes made here should be cherry-picked into the branch being updated.

master updated, now going to the 8x to cherry-pick and then push to the branch.

**Comment by helio-frota** [comment]
maybe I did another thing wrong because github is showing a 'change' with no 'changes'


```console
✔ ~/d/centos7-s2i-nodejs [master|✔] 
16:42 $ git checkout 8.x 
Switched to branch '8.x'
Your branch is up-to-date with 'origin/8.x'.
✔ ~/d/centos7-s2i-nodejs [8.x|✔] 
16:42 $ git pull origin 8.x 
From github.com:bucharest-gold/centos7-s2i-nodejs
 * branch            8.x        -> FETCH_HEAD
Already up-to-date.
✔ ~/d/centos7-s2i-nodejs [8.x|✔] 
16:43 $ git rebase origin/8.x 
Current branch 8.x is up to date.
✔ ~/d/centos7-s2i-nodejs [8.x|✔] 
16:43 $ git cherry-pick e19093502af5c94cc03fd833367c7c4baf1c77f0
[8.x d952a5f] (chore): update node versions
 Date: Thu Aug 10 16:35:09 2017 -0300
 3 files changed, 10 insertions(+), 9 deletions(-)
✔ ~/d/centos7-s2i-nodejs [8.x ↑·1|✔] 
16:43 $ git commit -a -m "(chore) update to Node.js 8.3.0"
On branch 8.x
Your branch is ahead of 'origin/8.x' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
✘-1 ~/d/centos7-s2i-nodejs [8.x ↑·1|✔] 
16:45 $ git push origin 8.x 
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 556 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:bucharest-gold/centos7-s2i-nodejs.git
   2e75a2b..d952a5f  8.x -> 8.x
```

![foo](https://user-images.githubusercontent.com/6443576/29189298-57d64674-7dec-11e7-9c4e-2e36dac0b31c.png)

when I click on compare and select the 8.x branch:

![bar](https://user-images.githubusercontent.com/6443576/29189323-68a0ff8a-7dec-11e7-8284-96989a03ff68.png)

**Comment by helio-frota** [comment]
the problem with the first time was 'origin/8.x' instead only '8.x' : /
