### ISSUE TITLE
Update publishing guide

### ISSUE THREAD

**Issue by lance** [bucharest-gold/centos7-s2i-nodejs#26]
It is quite out of date

**Comment by chargio** [comment]
And it doesn't work

**Comment by lance** [comment]
@chargio what exactly doesn't work, and how does it behave? From your message it sounds like perhaps you are referring to [this](https://github.com/bucharest-gold/centos7-s2i-nodejs#installation), but I am not sure.

**Comment by chargio** [comment]
Yes, when I do th installation following those instructions, the imagestream is not there.
``` oc get is```
would sshow it

But it is not in the catalogue. I can't find it in seach, not javascript, not uncategorized

**Comment by lance** [comment]
@chargio that is not really relevant to the publishing guide - which is just to document how we do a release of this stuff a little bit better. It is, however a problem that I have duplicated. I created a new issue for it [here](https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/28).

**Comment by lance** [comment]
@chargio if you would like to track the upstream issue it is here: https://github.com/openshift/origin/issues/17905

**Comment by chargio** [comment]
Thanks @lance

**Comment by lance** [comment]
Fixed in https://github.com/bucharest-gold/centos7-s2i-nodejs/pull/66
