### ISSUE TITLE
Run npm run-script build during build

### ISSUE THREAD

**Issue by chargio** [bucharest-gold/centos7-s2i-nodejs#32]
The current build does not execute  `npm run-script build`
In order to make it work, you need to manually connect and execute it on the pod. New builds with new dependencies can fail because of that.

Using a post deployment hook returns `

```

container_linux.go:247: starting container process caused "exec: \"npm run-script build\": executable file not found in $PATH"
--


```

**Comment by lance** [comment]
I'm not sure I understand what you are describing. Can you please tell me how to reproduce this?

**Comment by lance** [comment]
@chargio I can take care of this. It's been a long day. :)

**Comment by chargio** [comment]
I've discovered it does not work if memory is under 512MiB - 1024GiB
So it does not work in openshift online... as the quota limit is 512MiB max

I can't see how to solve that.

**Comment by lance** [comment]
@chargio when you say "it doesn't work", do you mean the entire builder image doesn't work? Or just running `npm run-script build` doesn't work?

**Comment by chargio** [comment]
Running:
```npm run-script build```

never finish, and you get a time out (and the pod is killed). I've tried modifying both the assemble script and the run script and the result is the same. In minishift you get the same problem (with 2GB of memory for the minishift VM).

It does not happen with minishift on 3.7, but it does not work in openshift online.

**Comment by lance** [comment]
I will look into this today, but I wonder if the problem is less about
`run-script` and more about the fact that patternfly is very big. Just a
thought...

>

**Comment by chargio** [comment]
I've tried too with react-demo-script

**Comment by lance** [comment]
@chargio what about adding a `postinstall: npm run build` - have you tried that?

**Comment by chargio** [comment]
I tried that too, but I got an error, it couldn't find npm.

**Comment by chargio** [comment]
What about a ENV VARIABLE

you could do run build if there is variable called: build_assets, and the parameter could be the actual order 'npm run build' or just 'build'

**Comment by lholmquist** [comment]
"I tried that too, but I got an error, it couldn't find npm." can't you add "npm" as a dev dependecy to the project, then the postinstall script should see it

**Comment by chargio** [comment]
I will try that, thanks, but I was expecting that to be easier, for instance, you can't configure secrets in the build...

**Comment by lance** [comment]
@chargio I have added a test that exercises the `postinstall` script in this commit https://github.com/bucharest-gold/centos7-s2i-nodejs/commit/786c3898a8d7d53a92de0126a38f769307e16931 and it works without issue. Can you please try using `postinstall` again? This should work for you.

It's not clear to me what the issue is with secret config. Can you be clearer about what you want to achieve?

**Comment by lance** [comment]
@chargio ping - checking to see if you have had any success here. I would like to close this if possible, but want to make sure we've got you going.

**Comment by chargio** [comment]
@lance I can't start a new install right now, we are in the middle of development. Close it and I will try again later

**Comment by chargio** [comment]
@lance I am not writing the code. Close it and I will try again later

**Comment by chargio** [comment]
@lance I made this work. I was using an Openshift postinstall, not a node.js postinstall, and thus it didn't work. I tried with a node postinstall script and it worked.
It should be documented, anyway.
