### ISSUE TITLE
Permission issues when running NODE_ENV=development and DEV_MODE=true

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/centos7-s2i-nodejs#61]
i'm working on this nodeshift issue, https://github.com/bucharest-gold/nodeshift/issues/208 to get buildConfig env vars, so i set NODE_ENV=development in my buildConfig and the build phase works fine with installing dev deps.  

But during the pod deploy, i get permission issues now, when trying to load with nodemon(since DEV_MODE=true is set because of the development node env)

![screen shot 2018-03-27 at 8 49 01 am](https://user-images.githubusercontent.com/1037138/37968673-cdc25bfc-319c-11e8-9a2b-d92a527fc9b6.png)

i thought by moving https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L61 down a little, it would fix it. but i'm either doing something wrong, which is very possible, or that wasn't the problem

**Comment by lance** [comment]
Related: https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/38

**Comment by lance** [comment]
@lholmquist I think this is what is biting us. I wonder if doing `npm cache clean` at the end of the [assemble script](https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L64) might work. Is it easy enough to try that locally?

**Comment by lholmquist** [comment]
let me try.

**Comment by lholmquist** [comment]
I think i got something working here.

https://github.com/lholmquist/centos7-s2i-nodejs/commit/4a3b1e8d95c612f81d5f0f39c435b9c7fa19b316

Basically, i moved the block of code that cleaned the npm cache and then fixed the write permissions down a little, so both a "production" and "development" environment will run it

**Comment by lance** [comment]
Fixed in: https://github.com/bucharest-gold/centos7-s2i-nodejs/commit/db8b853312b893548434cf7e55b130fd1683bf2b

**Comment by lance** [comment]
@lholmquist new images have been pushed for `latest`, `9.x` and `8.x`.
