### ISSUE TITLE
Signals not received because scripts are not running under pid 1

### ISSUE THREAD

**Issue by reneklootwijk** [bucharest-gold/centos7-s2i-nodejs#84]
The way a node script is executed results in the node script not running under pid 1.
This is an example of the process table:
UID        PID  PPID  C STIME TTY          TIME CMD
default      1     0  0 07:14 ?        00:00:00 /usr/bin/scl enable rh-git29 -- 
default      7     1  0 07:14 ?        00:00:00 /bin/bash /var/tmp/scl2s24MJ
default     10     7  1 07:14 ?        00:00:00 node svc.js

When a container is killed docker will send the SIGTERM signal to pid 1 in order to enable a graceful shutdown. However, because the script does not run under pid 1, this signal never reaches the script and the script cannot issue a graceful shutdown. This might not be an issue for lots of scripts, but for some, including mine, it is because it has to do some cleaning up activities before shutting down.

**Comment by bobmcwhirter** [comment]
```
13:49 bobmcw: lholmquist: I've seen similar if I just run something, instead of 'exec thingy' as the last line of a script
13:49 bobmcw: e.g.
13:49 bobmcw: java -jar whatever.jar
13:49 bobmcw: vs
13:49 bobmcw: exec java -jar whatever.jar
13:50 bobmcw: 1st makes a sub-process, exec will replace
```

**Comment by bobmcwhirter** [comment]
Sorry for the java-centric comment, it's what I know.

**Comment by lance** [comment]
@reneklootwijk I have noticed the behavior, but had no idea why. Thank you for pointing this out. I worry that this might be a side effect of `s2i`, but am not sure. I will take a look.

**Comment by reneklootwijk** [comment]
I use s2i all the time and never had this issue. When using the other nodejs image, I mentioned,  there is no issue.

**Comment by lance** [comment]
Okay thanks for that info. I will take a look today to see what I can find

**Comment by lance** [comment]
@reneklootwijk we think this might be a fix for you https://github.com/bucharest-gold/centos7-s2i-nodejs/tree/git-test. I have tested by using a builder image built from this branch, deploying a simple app to openshift, logging in to the running pod and viewing the running processes via `top`. Here's what I see. I think this is more like what you are looking for.

```
top - 21:30:30 up  3:09,  0 users,  load average: 0.29, 0.30, 0.40
Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.9 sy,  0.0 ni, 98.3 id,  0.0 wa,  0.0 hi,  0.5 si,  0.0 st
KiB Mem :  6103604 total,   120720 free,   906596 used,  5076288 buff/cache
KiB Swap:  2453704 total,  2410352 free,    43352 used.  4148800 avail Mem

  PID     USER  PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+                                                                 COMMAND
    1 1000070+  20   0 1062836  50676  19408 S   0.0  0.8   0:00.50                                                                     npm
   15 1000070+  20   0  678420  25020  17764 S   0.0  0.4   0:00.07                                                                    node
   21 1000070+  20   0   11772   2900   2532 S   0.0  0.0   0:00.01                                                                      sh
   31 1000070+  20   0   51924   3752   3188 R   0.0  0.1   0:00.02                                                                     top
```

**Comment by lance** [comment]
@reneklootwijk can you confirm whether this fix (on 8.x, 8.x, 10.x and latest) has resolved your issue.
