### ISSUE TITLE
Restoring build artifacts fails if no postinstall script exists

### ISSUE THREAD

**Issue by lance** [bucharest-gold/centos7-s2i-nodejs#89]
When a build is being recreated on openshift and we are restoring existing artifacts from the image cache, we [explicitly call](https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L48) `npm run postinstall` even if no `postinstall` script exists.

A workaround for this is to add a noop `postinstall` script to your package.json

**Comment by lincolnthree** [comment]
It works!

```
    "postinstall": "echo 'Cleaning up.'"
```

**Comment by lance** [comment]
Fixed in https://github.com/bucharest-gold/centos7-s2i-nodejs/commit/2125b6d591b95df92629c4526f6ff4725529b81e
